dist: bionic
language: sh

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      script:
        - make test

    - stage: deploy
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        file: envx
        on:
          tags: true
          condition: $TRAVIS_TAG =~ v[0-9].*
